apiVersion: v1
kind: Pod
metadata:
  name: nginx-no-requests-no-limits
  labels:
     app: nginx
spec:
  containers:
  - name: nginx
    image: registry.cloudyuga.guru/library/nginx:alpine
    ports:
    - containerPort: 80
