apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     app: nginx
  annotations:
    build: demo
    builder: cloudyuga
spec:
  containers:
  - name: nginx-demo
    image: registry.cloudyuga.guru/library/nginx:alpine
    ports:
    - containerPort: 80
