apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  labels:
    env: test
spec:
  containers:
  - name: pod-node
    image: registry.cloudyuga.guru/library/nginx:1.9.1
  nodeSelector:
    disktype: ssd
