apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
     app: nginx
spec:
  containers:
  - name: nginx-demo
    image: registry.cloudyuga.guru/library/nginx:alpine
    ports:
    - containerPort: 80
